### ISSUE TITLE
Audio tracks contain no bitrate information

### ISSUE THREAD

**Issue by jamie-usp** [unifiedstreaming/live-demo-cmaf#1]
Unified Origin requires the presence of avgBitrate to be signaled in the esds box. Currently FFmpeg only signals maxBitrate. 

Need raising/escalating to FFlabs.

**Comment by jeeb** [comment]
This was fixed by adding fall-backs for average bit rate calculation in http://git.videolan.org/?p=ffmpeg.git;a=commit;h=308882d9f2c6cc7159aba2ca7cdc99d07a9b531e . I was honestly surprised the existing logic actually attempted to calculate the average bit rate from existing data.

Of course, in case of fragmented mp4 where you write your sample description boxes in the beginning, such data is not available, so fall-backs are required.

**Comment by RufaelDev** [comment]
Thanks we will check this out, 

For your interest/info the MPEG group also want to add text to isobmff to also 
allow a target value to be set especially for live when you don't know the exact average bit-rate from the data:

https://github.com/MPEGGroup/FileFormat/issues/18

There is some agreement around this issue and we think it will be merged in the next corrigendum for isobmff, 
having an approximate value should not break existing implementation, target value can be the target bit-rate.
In this case fallback can truly be optional.

**Comment by jamie-usp** [comment]
Thanks @jeeb using the latest build, i've successfully tested and updated all our Interface2 encoding setting so with have an ABR ladded. 

This can be seen in commit: https://github.com/unifiedstreaming/live-demo-cmaf/commit/65a7fbe7d5a92878690e853a26b2b5d1414f246b
